import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-healthcare-payer-contract-underpayment-recovery",
  "engine": "recovery",
  "title": "Healthcare Payer Contract Underpayment Recovery",
  "shortTitle": "Payer Underpayment Recovery",
  "tagline": "Find, prove, appeal, and collect every contractually owed reimbursement",
  "industry": "Healthcare Revenue Integrity",
  "uiPort": 4551,
  "apiPort": 5551,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Recovered payer underpayments with defensible contract and claim-level evidence",
  "valueNarrative": "Turn contracts, claims, remittances, clinical documentation, and appeal deadlines into verified reimbursement recovery.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAllowedAmount",
    "actualLabel": "Payer paid amount",
    "expectedLabel": "Contract expected amount",
    "varianceLabel": "Potential underpayment",
    "direction": "expected-minus-actual",
    "finding": "Contract terms and remittance evidence indicate a potential payer underpayment.",
    "actions": [
      "Reprice the claim against the effective contract",
      "Validate coding, authorization, and clinical evidence",
      "Submit the payer appeal before the contractual deadline",
      "Reconcile additional reimbursement to cash"
    ]
  }
},[
feature("contract-ingestion-and-versioning","PUR01","Contract ingestion & versioning","Reconcile contract ingestion & versioning using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed contract ingestion & versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("claim-and-835-remittance-ingestion","PUR02","Claim and 835 remittance ingestion","Reconcile claim and 835 remittance ingestion using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed claim and 835 remittance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("contractual-claim-repricing","PUR03","Contractual claim repricing","Reconcile contractual claim repricing using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed contractual claim repricing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("drg-and-case-rate-validation","PUR04","DRG and case-rate validation","Reconcile drg and case-rate validation using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed drg and case-rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("fee-schedule-validation","PUR05","Fee-schedule validation","Reconcile fee-schedule validation using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed fee-schedule validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("bundling-and-carve-out-analysis","PUR06","Bundling and carve-out analysis","Reconcile bundling and carve-out analysis using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed bundling and carve-out analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("stop-loss-and-outlier-calculation","PUR07","Stop-loss and outlier calculation","Reconcile stop-loss and outlier calculation using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed stop-loss and outlier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("denial-and-adjustment-classification","PUR08","Denial and adjustment classification","Reconcile denial and adjustment classification using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed denial and adjustment classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("authorization-evidence-control","PUR09","Authorization evidence control","Reconcile authorization evidence control using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed authorization evidence control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("timely-filing-deadline-control","PUR10","Timely-filing deadline control","Reconcile timely-filing deadline control using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed timely-filing deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("underpayment-case-workbench","PUR11","Underpayment case workbench","Reconcile underpayment case workbench using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed underpayment case workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("payer-appeal-package-generation","PUR12","Payer appeal package generation","Reconcile payer appeal package generation using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed payer appeal package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("payer-response-tracking","PUR13","Payer response tracking","Reconcile payer response tracking using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed payer response tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("cash-posting-reconciliation","PUR14","Cash posting reconciliation","Reconcile cash posting reconciliation using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed cash posting reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]}),
feature("recovery-and-root-cause-analytics","PUR15","Recovery and root-cause analytics","Reconcile recovery and root-cause analytics using effective payer contracts, 837 claims, 835 remittances, coding, authorization, and clinical evidence.","Produce a governed recovery and root-cause analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["payer","Payer","text","Apex Health Plan"],["claimNumber","Claim Number","text","CLM-2026-88412"],["paidAmount","Paid Amount","currency",74250],["expectedAllowedAmount","Expected Contract Allowed","currency",96800]],{amountField:"paidAmount",subjects:["Commercial inpatient claim","Medicare Advantage encounter","Outpatient surgery claim","Emergency services claim","Professional claim"]})
]);
